---
name: OpenDcs Algorithms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 11
          distribution: temurin      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.1
        with:
          dependency-graph: generate-and-submit
      - name: Test Algorithms
        run: ./gradlew test --info
        working-directory: ./algorithms
