---
name: App starter (CWBI Test)

on:
  push:
    branches:
      - cwbi-test
  pull_request:
    branches:
      - cwbi-test

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.2
      - name: test
        working-directory: appstarter/internal
        run: go test -v
  build:
    name: Build container
    runs-on: ubuntu-latest
    needs: test
    steps:
    # TODO: only need 4 fixed name images "api, apps, lrgs, and migration"
    # apps will cover compdepends, compproc and routing scheduler
      - uses: actions/checkout@v4
      - name: Build apps container
        run: docker build -t ghcr.io/wm/usace-watermagement/compdepends:latest --target=apps .
      - name: Build lrgs container
        run: docker build -t ghcr.io/usace-watermanagement/opendcs/lrgs:latest --target=lrgs .
      - name: Build migrations container
        run: docker build -t ghcr.io/usace-watermanagement/opendcs/migration:latest --target=migration .
